spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: 'true'
    hibernate:
      ddl-auto: update

jwt:
  token:
    secret-key: 5yQXIefRFbsJaeGQNBCoEcF2pr0f3hgR5yQXIefRFbsJaeGQNBCoEcF2pr0f3hgR
    expiration: '864000000'
  refresh-token:
    expiration: '604800000'

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  password: ${REDIS_PASSWORD}
  connectTimeoutInSecond: 60 # ms
  ttl-menus: 1440 # 1 day

# Debug for spring security
#logging:
#  level:
#    org:
#      springframework:
#        security: TRACE

## Change the default port
#server:
#  port: 8081

info:
  app:
    version: 1.0.0
