spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: ${SQL_DATABASE_URL}
    username: ${SQL_USERNAME}
    password: ${SQL_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: 'true'
    hibernate:
      ddl-auto: update

jwt:
  token:
    secret-key: 5yQXIefRFbsJaeGQNBCoEcF2pr0f3hgR5yQXIefRFbsJaeGQNBCoEcF2pr0f3hgR
    expiration: '864000000'
  refresh-token:
    expiration: '604800000'

redis:
  host: ${REDIS_HOST} # Default to "localhost" if not provided
  port: ${REDIS_PORT}      # Default to "6379" if not provided
  connectTimeoutInSecond: 60 # ms