spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:postgresql://${SQL_HOST}:${SQL_PORT}/${SQL_DATABASE}
    username: ${SQL_USERNAME}
    password: ${SQL_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: 'true'
    hibernate:
      ddl-auto: update

jwt:
  token:
    secret-key: 5yQXIefRFbsJaeGQNBCoEcF2pr0f3hgR5yQXIefRFbsJaeGQNBCoEcF2pr0f3hgR
    expiration: '864000000'
  refresh-token:
    expiration: '604800000'

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  password: ${REDIS_PASSWORD}
  connectTimeoutInSecond: 60 # ms